# Generated by Django 5.1.2 on 2024-11-11 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contribuyente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(max_length=50, unique=True)),
                ('nombre1', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre2', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido1', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido2', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
